remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  '@ts-stadium on GitHub':
    - 'https://github.com/no-day/ts-stadium'
  'Blog with Demos':
    - 'https://no-day.github.io/ts-stadium/demo'

color_scheme: dark-custom
