remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  '@ts-stadium on GitHub':
    - '{{{ GITHUB_LINK }}}'
  'Blog with Demos':
    - '{{{ DEMO_LINK }}}'

color_scheme: dark-custom
