name: Test

on:
  push:
    branches: ['main', $default-branch]
  pull_request:
    branches: ['main', $default-branch]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [
  #           # 12.x,
  #           # 14.x,
  #           15.x,
  #         ]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: yarn install
  #     - run: yarn run build
  #     - run: yarn test

  publish:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      # - name: Install
      #   run: yarn install

      # - run: yarn lerna publish from-package --yes --no-verify-access

  deploy-docs:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Install
        run: yarn install

      - run: yarn public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public
